INSERT INTO test_questions (text) VALUES ('Вы планируете вывести основную часть денег из инвестиционного портфеля через...');
INSERT INTO test_questions (text) VALUES ('Готовы ли вы рисковать, чтобы получить высокую прибыль?');
INSERT INTO test_questions (text) VALUES ('Есть ли у вас постоянный доход?');
INSERT INTO test_questions (text) VALUES ('Ваш возраст?');
INSERT INTO test_questions (text) VALUES ('Какую часть своих сбережений Вы готовы инвестировать?');
INSERT INTO test_questions (text) VALUES ('Есть ли у вас опыт на бирже?');
INSERT INTO test_questions (text) VALUES ('Оцените свои знания в области инвестирования и финансов?');

INSERT INTO test_answers (name, score, test_question_id) VALUES ('Меньше, чем через год', 3, 1);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Через 1-3 года', 2, 1);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Через 4 года и более', 1, 1);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Да, это моя основная цель', 3, 2);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Суммой, не больше половины от моего инвест капитала', 2, 2);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Нет', 1, 2);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Да, больше 70 т.р. в месяц', 3, 3);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Да, меньше 70 т.р. в месяц', 2, 3);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Нет или он меньше 30 т.р. в месяц', 1, 3);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Моложе 25 лет', 3, 4);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('25-40 лет', 2, 4);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Более 40 лет', 1, 4);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Более 50%', 3, 5);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('20-50%', 2, 5);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Менее 20%', 1, 5);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Да, более 2-х лет', 3, 6);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Да, 1-2 года', 2, 6);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Нет или меньше 1 года', 1, 6);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Есть экономическое образование или опыт работы в финансовой сфере', 3, 7);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Есть знания, полученные из жизненного опыта', 2, 7);
INSERT INTO test_answers (name, score, test_question_id) VALUES ('Я не уверен в своих знаниях', 1, 7);
